---
# Source: jenkins-agent/templates/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: agent01
  namespace: jenkins
  labels:
    name: agent01
spec:
  containers:
  - name: agent01
    image: DOMAIN/jnlp-slave:latest
    env:
      - name: JENKINS_URL
        value: "http://jenkins:8080"
      - name: JENKINS_AGENT_NAME
        value: "agentXX"
      - name: JENKINS_SECRET
        value: "dXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxa27a10f20"
    volumeMounts:
     - name: config-volume
       mountPath: /home/jenkins/.kube/config
     - name: dockersocket
       mountPath: /var/run/docker.sock
  volumes:
    - name: config-volume
      configMap:
        name: management-qa
    - name: dockersocket
      hostPath:
        path: /var/run/docker.sock
