apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.nodeName }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.nodeName }}
spec:
  containers:
  - name: {{ .Values.nodeName }}
    image: {{ .Values.image }}
    env:
      - name: JENKINS_URL
        value: "http://jenkins:8080"
      - name: JENKINS_AGENT_NAME
        value: "{{ .Values.nodeName }}"
      - name: JENKINS_SECRET
        value: "{{ .Values.nodeSecret }}"
    volumeMounts:
     - name: config-volume
       mountPath: /home/jenkins/.kube/config
  volumes:
    - name: config-volume
      configMap:
        name: {{ .Values.configMap }}
